from enum import Enum


class CallBackCode(Enum):
	UNKNOW_ERROR = 0
	MUSIC_LIST_RETURN = 1
	MUSIC_LRC_RETURN = 2
	REQUEST_ERROR = 3
	MUSIC_PATH_RETURN = 4
	MUSIC_PATH_END = 5
	MUSIC_SERACH_CURRENT = 6
	MUSIC_LRC_ERROR = 7
	MUSIC_LRC_FINISHED = 8
	MUSIC_COPY_FILE = 9
	MUSIC_COPY_ERROR = 10
	MUSIC_COPY_FINISHED = 11
	PLAYER_M2U_FINISHED = 12
